name: Ejecutar pruebas

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar caché de dependencias Maven
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Configurar JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache SonarQube packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Compilar y empaquetar la app
      run: mvn clean package -DskipTests

    - name: Iniciar la app en segundo plano
      run: java -jar target/health-1.0-SNAPSHOT.jar &
    
    - name: Esperar que la app esté disponible
      run: |
        for i in {1..10}; do
          nc -z localhost 8080 && echo "App levantada" && exit 0
          echo "Esperando que la app se levante..."
          sleep 3
        done
        echo "La app no se levantó a tiempo" && exit 1

    - name: Ejecutar pruebas unitarias y funcionales
      run: mvn test
      env:
        DISPLAY: :99

    - name: Generar reporte HTML de pruebas
      if: always()
      run: mvn surefire-report:report
    - name: Subir reporte HTML
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: reporte-pruebas-html
        path: target/site/

    - name: Analisis estatico con SonarQube
      if: always()

      run: mvn compile sonar:sonar -Dsonar.projectKey=GeraldOpitz_HealthCare -Dsonar.organization=geraldopitz -Dsonar.host.url=https://sonarcloud.io
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}