name: Ejecutar pruebas

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Instalar dependencias Maven
      run: mvn install -DskipTests

    - name: Construir la app
      run: mvn clean package -DskipTests

    - name: Iniciar la app en segundo plano
      run: java -jar target/health-1.0.jar &

    - name: Esperar que la app esté disponible
      run: |
        for i in {1..10}; do
        nc -zv localhost 8080 && break
        sleep 2
        done

    - name: Ejecutar pruebas
      run: mvn test
      env:
        DISPLAY: :99
